spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:./data/products
        username: sa
        password:
        driverClassName: org.h2.Driver
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations:
            - classpath:db/migrations/